import { Agent , run } from "@openai/agents";
import type { OutputGuardrail } from "@openai/agents";
import "dotenv/config";
import { z } from "zod";
// types
const ResponseOutput = z.object({ response: z.string() });
type ResponseOutput = z.infer<typeof ResponseOutput>;

// Guardrails
const guardrailAgent = new Agent({
    name: 'Guardrail check',
    instructions: `You are a Guardrail Agent for a Finance Research system. Your role is to review, validate, and filter outputs generated by research agents before they are delivered to the user. You do not generate financial analysis yourself. You only approve, modify, or reject responses to ensure they are safe, compliant, and reliable.

    Reject any response that guarantees returns, claims risk-free profits, provides personalized investment advice, includes fabricated or uncited financial data, or encourages illegal activities such as insider trading, tax evasion, or market manipulation. Also reject content that uses hype, urgency tactics, or promotional language to push specific assets.

    If the response is generally acceptable but lacks proper risk acknowledgment, uses overly confident predictions, presents forecasts as certainties, or omits uncertainty, modify it instead of rejecting it. Rewrite such content to be neutral, educational, and probabilistic in tone. Ensure that estimates are clearly labeled, assumptions are stated, and risks are explicitly mentioned.

    No unverifiable numerical claims should be allowed. If real-time or up-to-date financial data cannot be confirmed, require verification from a reliable financial source. The final output must clearly indicate whether the response is approved, modified (with corrections), or rejected (with reason).`,
    outputType: ResponseOutput,
  });
const outputGuardrail: OutputGuardrail<typeof ResponseOutput> = {
    name:"ResponseGuardrail",
    async execute({ agentOutput, context }) {
        const result = await run(guardrailAgent, agentOutput.response, {
          context,
        });
        return {
          outputInfo: result.finalOutput,
          tripwireTriggered: result.finalOutput?.response.includes('math') ?? false,
        };
      },
}
// main Agent
const Deep_Agent = new Agent({
    name: "deepAgent",
    instructions: "You are a deep research agent that can answer questions deeply and thoroughly.",
    model: "gpt-5-mini",
    tools:[],
    outputType: z.object({
        response: z.string(),
        confidence: z.number(),
    }),
    outputGuardrails: [outputGuardrail],
});
export default Deep_Agent;